### model
model_name_or_path: AIDC-AI/Marco-o1
### method
stage: wsft
do_train: true
finetuning_type: full
deepspeed: examples/deepspeed/ds_z3_config.json
use_adam_mini: true

### dataset
dataset: Marco-iter0-MATH-train-K-16-loft-alpha-5-k-2
template: qwen
cutoff_len: 3072
max_samples: 10000
overwrite_cache: true
preprocessing_num_workers: 16
packing: false

### output
output_dir: ../SimpleO1/saves/math/Marco-loft-iter0-alpha_5-ppo-normed
logging_steps: 2
save_strategy: "no"
plot_loss: true
overwrite_output_dir: true
save_only_model: true

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 8
learning_rate: 2.0e-7
num_train_epochs: 1.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
max_grad_norm: 10

### eval
val_size: 0.0001
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 50000
