### model
model_name_or_path: Qwen/QwQ-32B-Preview
### method
stage: dpo
# pref_loss:
do_train: true
# finetuning_type: full #lora
finetuning_type: freeze
freeze_trainable_layers: 36 #24
freeze_trainable_modules: all
deepspeed: examples/deepspeed/ds_z3_config.json
pref_beta: 0.1

### dataset
dataset: QwQ-iter0-MATH-train-K-16-dpo
template: qwen
cutoff_len: 3072
max_samples: 10000 #10000 #10000
overwrite_cache: true
preprocessing_num_workers: 16
packing: false

### output
output_dir: ../SimpleO1/saves/math/QwQ-dpo
logging_steps: 2
save_strategy: "no"
plot_loss: true
overwrite_output_dir: true
save_only_model: true

### train
per_device_train_batch_size: 1 #2
gradient_accumulation_steps: 4 #4
learning_rate: 2.0e-7 #1.0e-4
num_train_epochs: 2.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
max_grad_norm: 10

### eval
val_size: 0.0001
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 50000